<?php

/**
 * Helper function to get the slider content.
 */
function _tns_main_settings_get_eventos_main_carousel(){ 
  $nodes = node_load_multiple(array(), array(
      'type' => 'evento',
  ));
  
  print theme('eventos_main_carousel', array('nodes' => $nodes));  
}

function _tns_main_settings_quienes_somos(){ 
  $output = array();
  
  print theme('quienes_somos', array('output' => $output));  
}

function _tns_main_settings_presentacion_propuestas(){ 
  $output = array();
  module_load_include('inc', 'node', 'node.pages'); 
  $node_form = new stdClass;
  $node_form->type = 'propuesta';
  $node_form->language = LANGUAGE_NONE;
  $form_suscripcion = drupal_get_form('propuesta_node_form', $node_form);
  $form = drupal_render($form_suscripcion);  
  print theme('presentacion_propuestas', array('output' => $output, 'form' => $form));   
}

function _tns_main_settings_suscripcion_form(){
  $output = array();
  module_load_include('inc', 'node', 'node.pages'); 
  $node_form = new stdClass;
  $node_form->type = 'suscripcion';
  $node_form->language = LANGUAGE_NONE;
  $form_suscripcion = drupal_get_form('suscripcion_node_form', $node_form);
  $form = drupal_render($form_suscripcion);
  print theme('suscripcion', array('output' => $output, 'form' => $form));  
}

function _tns_main_settings_contactanos(){ 
  $output = array();
  
  print theme('contactanos', array('output' => $output));  
}